app = "setu-auth-2"
primary_region = "fra"

[build]
  dockerfile = "../../Dockerfile"

[env]
  SETU_AUTHORITY = "auth-2"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
